### ISSUE TITLE
Is "SPMT" spearmint? 

### ISSUE THREAD

**Issue by pswpswpsw** [Pattio/DeepSwarm#7]
Since it is not referenced, so I have this question in the paper. 

If so that would be very amazing, the comparison between PSO and Bayesian Optimization has been validated in SigOpt's paper where two of them were very close instead of such a big gap in your paper. However, they didn't optimize topology but only the number of hidden units. I think maybe this is the main reason why NAS requires a different techniques than traditional ML where topology is hard-wired in the model itself.

**Comment by Pattio** [comment]
Hi, I am sorry that it was not described in great detail (due to the page limit), but as mentioned in Section 4 we used the baselines from [Auto-Keras](https://arxiv.org/pdf/1806.10282). In Section 5 of their paper you will see more details (note that each method was run for 12 hours on a single GPU). And regarding your last point, yes I agree with you. I hope that answers your question 👍
